# Generated by Django 5.2.1 on 2025-05-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='passports/')),
                ('passport_number', models.CharField(blank=True, max_length=50)),
                ('surname', models.CharField(blank=True, max_length=100)),
                ('given_names', models.CharField(blank=True, max_length=100)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.CharField(blank=True, max_length=50)),
                ('place_of_birth', models.CharField(blank=True, max_length=100)),
                ('date_of_issue', models.CharField(blank=True, max_length=50)),
                ('date_of_expiry', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
